apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-html-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-html
  template:
    metadata:
      labels:
        app: my-html
    spec:
      containers:
      - name: my-html
        image: rajatmishra/my-html-app:1.0
        ports:
        - containerPort: 80
