name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Say Hello
        run: echo "🚀 Build started for Hello World app"

      - name: Show current directory
        run: pwd

      - name: List project files
        run: ls -la "$GITHUB_WORKSPACE"
